version: "3"

services:
    zookeeper:
        image: ruanpienaar/zookeeper
        hostname: zookeeper.docker
        network_mode: bridge
        ports:
          - "2181:2181"

    kafka-broker-1:
        depends_on:
            - zookeeper
        image: ruanpienaar/kafka-server
        hostname: kafka-broker-1
        network_mode: bridge
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper.docker
          BROKER_ID: 1
        ports:
          - "9092"

    kafka-broker-2:
        depends_on:
            - zookeeper
        image: ruanpienaar/kafka-server
        hostname: kafka-broker-2
        network_mode: bridge
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper.docker
          BROKER_ID: 2
        ports:
          - "9093"

    kafka-broker-3:
        depends_on:
            - zookeeper
        image: ruanpienaar/kafka-server
        hostname: kafka-broker-3
        network_mode: bridge
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper.docker
          BROKER_ID: 3
        ports:
          - "9094"

    schema-registry:
      image: confluentinc/cp-schema-registry:5.1.2
      hostname: schema-registry
      network_mode: bridge
      depends_on:
        - zookeeper
        - kafka-broker-1
        - kafka-broker-2
        - kafka-broker-3
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

    rest-proxy:
      image: confluentinc/cp-kafka-rest:5.1.2
      network_mode: bridge
      depends_on:
        - zookeeper
        - kafka-broker-1
        - kafka-broker-2
        - kafka-broker-3
        - schema-registry
      ports:
        - 8082:8082
      hostname: rest-proxy
      environment:
        KAFKA_REST_HOST_NAME: rest-proxy
        KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka-broker-1:9092,kafka-broker-1:9092,kafka-broker-1:9092'
        KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
        KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

    kafka-topics-ui:
      image: landoop/kafka-topics-ui
      network_mode: bridge
      depends_on:
        - kafka-broker-1
        - kafka-broker-2
        - kafka-broker-3
        - rest-proxy
      ports:
        - "8000:8000"
      hostname: kafka-topics-ui
      environment:
        KAFKA_REST_PROXY_URL: 'http://rest-proxy:8082'
        PROXY: 'true'
    
    kafka-bin:
      tty: true
      stdin_open: true
      image: ruanpienaar/kafka-bin
      depends_on:
        - zookeeper
        - kafka-broker-1
        - kafka-broker-2
        - kafka-broker-3