version: "3"

services:
    zookeeper:
        image: ruanpienaar/zookeeper
        ports:
          - "2181:2181"

    kafka-server-1:
        depends_on: 
            - zookeeper
        image: ruanpienaar/kafka-server:broker_1
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper
          BROKER_ID: 1
        ports:
          - "9092:9092"
          
    kafka-server-2:
        depends_on: 
            - zookeeper
        image: ruanpienaar/kafka-server:broker_2
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper
          BROKER_ID: 2
        ports:
          - "9093:9093"
   
    kafka-server-3:
        depends_on: 
            - zookeeper
        image: ruanpienaar/kafka-server:broker_3
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper
          BROKER_ID: 3
        ports:
          - "9094:9094"
    
    schema-registry:
      image: confluentinc/cp-schema-registry:5.1.2
      hostname: schema-registry
      #container_name: schema-registry
      depends_on:
        - zookeeper
        - kafka-server-1
        - kafka-server-2
        - kafka-server-3
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
    
    rest-proxy:
      image: confluentinc/cp-kafka-rest:5.1.2
      depends_on:
        - zookeeper
        - kafka-server-1
        - kafka-server-2
        - kafka-server-3
        - schema-registry
      ports:
        - 8082:8082
      hostname: rest-proxy
      #container_name: rest-proxy
      environment:
        KAFKA_REST_HOST_NAME: rest-proxy
        KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka-server-1:9092'
        KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
        KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
        
    
    kafka-topics-ui:
      image: landoop/kafka-topics-ui
      depends_on: 
        - rest-proxy
      ports:
        - "8000:8000"
      hostname: kafka-topics-ui
      #container_name: kafka-topics-ui
      environment:
        KAFKA_REST_PROXY_URL: 'http://192.168.2.15:8082'
        PROXY: 'true'