version: "3.7"

services:
    zookeeper:
        image: ruanpienaar/zookeeper
        ports:
          - "2181:2181"

    kafka-broker-1:
        depends_on:
            - zookeeper
        image: kafka-server:latest
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper
          BROKER_HOSTNAME: localhost
          BROKER_PORT: 9092
          BROKER_ID: 0
        ports:
            - "9092:9092"

    kafka-broker-2:
        depends_on:
            - zookeeper
        image: kafka-server:latest
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper
          BROKER_HOSTNAME: localhost
          BROKER_PORT: 9093
          BROKER_ID: 1
        ports:
            - "9093:9093"

    kafka-broker-3:
        depends_on:
            - zookeeper
        image: kafka-server:latest
        environment:
          ZOOKEEPER_HOSTNAME: zookeeper
          BROKER_HOSTNAME: localhost
          BROKER_PORT: 9094
          BROKER_ID: 3
        ports:
            - "9094:9094"

    kafka-bin:
      tty: true
      stdin_open: true
      image: ruanpienaar/kafka-bin
      depends_on:
        - zookeeper
        - kafka-broker-1
        - kafka-broker-2
        - kafka-broker-3